# Namespace for the RHOAI operator
# The operator watches this namespace and redhat-ods-applications
apiVersion: v1
kind: Namespace
metadata:
  name: redhat-ods-operator
  labels:
    app: rhoai
    tutorial-level: "3"
    tutorial-module: "M4"
