apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tempomonolithic-traces-write
rules:
  - apiGroups: ['tempo.grafana.com']
    resources: [dev]
    resourceNames: [traces]
    verbs: ['create']
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tempomonolithic-traces-write
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tempomonolithic-traces-write
subjects:
  - kind: ServiceAccount
    name: otel-collector
    namespace: istio-system
