# Knative Eventing Broker -- central event bus for the project
# Events sent to this Broker are routed to subscribers via Triggers
apiVersion: eventing.knative.dev/v1
kind: Broker
metadata:
  name: default
  labels:
    app: event-broker
    tutorial-level: "2"
    tutorial-module: "M3"
  annotations:
    eventing.knative.dev/broker.class: MTChannelBasedBroker
spec: {}
