# Subscription -- connects a Channel to a subscriber service
# Delivers all events from the Channel to event-display
apiVersion: messaging.knative.dev/v1
kind: Subscription
metadata:
  name: pipeline-to-display
  labels:
    app: event-pipeline
    tutorial-level: "2"
    tutorial-module: "M3"
spec:
  channel:
    apiVersion: messaging.knative.dev/v1
    kind: Channel
    name: processing-pipeline
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: event-display
