apiVersion: v1
kind: Secret
metadata:
  name: shopinsights-secrets
  labels:
    app: shopinsights
    tutorial: personalized
    lesson: "01"
type: Opaque
stringData:
  API_KEY: "tutorial-secret-key-12345"
