# Velero restore from the dr-test-backup.
# Restores all namespaced resources and PVC data
# to the dr-test namespace.
apiVersion: velero.io/v1
kind: Restore
metadata:
  name: dr-test-restore
  namespace: openshift-adp
  labels:
    app: dr-test-app
    tutorial-level: "3"
    tutorial-module: "M3"
spec:
  backupName: dr-test-backup
  includedNamespaces:
    - dr-test
  restorePVs: true
  existingResourcePolicy: none
