apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-sdn
  labels:
    app: hello-sdn
    tutorial-level: "1"
    tutorial-module: "M4"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-sdn
  template:
    metadata:
      labels:
        app: hello-sdn
        tutorial-level: "1"
        tutorial-module: "M4"
    spec:
      containers:
        - name: httpd
          image: registry.access.redhat.com/ubi9/httpd-24:latest
          ports:
            - containerPort: 8080
