# PipelineRun — executes the clone-and-build pipeline
# Creates a VolumeClaimTemplate for the shared workspace
apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: clone-and-build-run-
  labels:
    app: tekton-tutorial
    tutorial-level: "2"
    tutorial-module: "M1"
    tekton.dev/pipeline: clone-and-build
spec:
  pipelineRef:
    name: clone-and-build
  params:
    - name: repo-url
      value: https://github.com/sclorg/nodejs-ex.git
    - name: revision
      value: master
    - name: image-name
      value: image-registry.openshift-image-registry.svc:5000/pipelines-tutorial/nodejs-ex
    - name: image-tag
      value: latest
  workspaces:
    - name: shared-workspace
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
