apiVersion: v1
kind: Service
metadata:
  name: orders-service
  labels:
    app: shopinsights
    component: orders-service
    tutorial: personalized
    lesson: "03"
spec:
  selector:
    app: shopinsights
    component: orders-service
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
