apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: products-data
  labels:
    app: shopinsights
    component: products-service
    tutorial: personalized
    lesson: "03"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: orders-data
  labels:
    app: shopinsights
    component: orders-service
    tutorial: personalized
    lesson: "03"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: analytics-data
  labels:
    app: shopinsights
    component: analytics-service
    tutorial: personalized
    lesson: "03"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
