# HyperConverged CR — activates all KubeVirt components after operator install
# This is the single CR that controls the entire OpenShift Virtualization deployment
apiVersion: hco.kubevirt.io/v1beta1
kind: HyperConverged
metadata:
  name: kubevirt-hyperconverged
  namespace: openshift-cnv
  labels:
    app: openshift-cnv
    tutorial-level: "3"
    tutorial-module: "M4"
spec:
  liveMigrationConfig:
    completionTimeoutPerGiB: 800
    parallelMigrationsPerCluster: 5
    parallelOutboundMigrationsPerNode: 2
    progressTimeout: 150
  certConfig:
    ca:
      duration: 48h0m0s
      renewBefore: 24h0m0s
    server:
      duration: 24h0m0s
      renewBefore: 12h0m0s
  featureGates:
    withHostPassthroughCPU: false
  infra: {}
  workloads: {}
