# Project (namespace) for the production environment
apiVersion: project.openshift.io/v1
kind: ProjectRequest
metadata:
  name: cicd-production
  labels:
    app: pipeline-demo
    tutorial-level: "2"
    tutorial-module: "M1"
    environment: production
