apiVersion: project.openshift.io/v1
kind: ProjectRequest
metadata:
  name: shopinsights-dev
  labels:
    app: shopinsights
    tutorial: personalized
    lesson: "01"
displayName: "ShopInsights Dev"
description: "Development environment for ShopInsights microservices"
