apiVersion: v1
kind: ResourceQuota
metadata:
  name: staging-quota
  namespace: shopinsights-staging
  labels:
    app: shopinsights
    tutorial: personalized
    lesson: "05"
spec:
  hard:
    pods: "10"
    requests.cpu: "4"
    requests.memory: 8Gi
    limits.cpu: "4"
    limits.memory: 8Gi
