#!/usr/bin/env bash
# migration-wave-plan.sh
# Demonstrates a migration wave planning approach for legacy app migration.
# In production, Konveyor/MTA generates this from assessment data.
# This script outputs an illustrative wave plan for educational purposes.

set -euo pipefail

BOLD="\033[1m"
GREEN="\033[0;32m"
YELLOW="\033[0;33m"
RED="\033[0;31m"
CYAN="\033[0;36m"
NC="\033[0m" # No Color

echo ""
echo -e "${BOLD}============================================================${NC}"
echo -e "${BOLD}     Legacy Application Migration Wave Plan${NC}"
echo -e "${BOLD}============================================================${NC}"
echo ""
echo -e "${CYAN}Assessment Summary:${NC} 12 applications evaluated"
echo -e "${CYAN}Assessment Tool:${NC}    Konveyor / MTA (Migration Toolkit for Applications)"
echo -e "${CYAN}Target Platform:${NC}   OpenShift 4.x"
echo ""

echo -e "${BOLD}------------------------------------------------------------${NC}"
echo -e "${GREEN}WAVE 1 -- Quick Wins (Weeks 1-2)${NC}"
echo -e "${BOLD}------------------------------------------------------------${NC}"
echo "  Risk: LOW    Effort: LOW    Strategy: Lift-and-Shift / Replatform"
echo ""
echo "  1. frontend-portal       (Node.js, stateless REST API)"
echo "     - Already runs as non-root"
echo "     - No filesystem dependencies"
echo "     - Migration: S2I build from Git, add Route"
echo ""
echo "  2. reporting-api          (Python Flask, stateless)"
echo "     - Reads from database, no local state"
echo "     - Migration: S2I with python:3.11-ubi9 builder"
echo ""
echo "  3. static-docs-site       (Static HTML/CSS/JS)"
echo "     - Migration: nginx UBI image, mount content"
echo ""

echo -e "${BOLD}------------------------------------------------------------${NC}"
echo -e "${YELLOW}WAVE 2 -- Standard Migrations (Weeks 3-6)${NC}"
echo -e "${BOLD}------------------------------------------------------------${NC}"
echo "  Risk: MEDIUM  Effort: MEDIUM  Strategy: Replatform"
echo ""
echo "  4. inventory-service      (Java Spring Boot, WAR on Tomcat)"
echo "     - Needs config externalization (hardcoded DB URL)"
echo "     - Migration: S2I with java:openjdk-17-ubi8 builder"
echo "     - Action: Extract config to ConfigMap, add health endpoints"
echo ""
echo "  5. notification-engine    (Java EE on JBoss EAP)"
echo "     - Uses JMS queues (needs AMQ Broker operator)"
echo "     - Migration: S2I with jboss-eap74-openjdk11 builder"
echo "     - Action: Deploy AMQ Broker, update JNDI settings"
echo ""
echo "  6. customer-portal        (PHP on Apache, sessions in files)"
echo "     - Writes session files to /tmp"
echo "     - Migration: S2I with php:8.1-ubi9, add emptyDir for sessions"
echo "     - Action: Add session affinity to Route"
echo ""

echo -e "${BOLD}------------------------------------------------------------${NC}"
echo -e "${RED}WAVE 3 -- Complex Migrations (Weeks 7-12)${NC}"
echo -e "${BOLD}------------------------------------------------------------${NC}"
echo "  Risk: HIGH   Effort: HIGH   Strategy: Replatform + Partial Refactor"
echo ""
echo "  7. legacy-billing         (Java EE, Oracle DB dependency)"
echo "     - Uses Oracle JDBC thin driver with TNS names"
echo "     - Writes invoices to NFS share"
echo "     - Migration: Custom S2I builder with Oracle client libs"
echo "     - Action: PVC for NFS, Secret for Oracle credentials"
echo ""
echo "  8. file-processor         (.NET Framework 4.8 on Windows)"
echo "     - Requires Windows container support"
echo "     - Migration: Rewrite to .NET 8 or run in OpenShift Virtualization"
echo "     - Action: Assess .NET Portability, decide rewrite vs VM"
echo ""
echo "  9. batch-etl-jobs         (Shell scripts + Python, runs as cron)"
echo "     - 15 cron jobs with complex scheduling"
echo "     - Migration: Convert to OpenShift CronJobs"
echo "     - Action: Map cron schedules, add resource limits"
echo ""

echo -e "${BOLD}------------------------------------------------------------${NC}"
echo -e "${RED}WAVE 4 -- Refactor Candidates (Weeks 13+)${NC}"
echo -e "${BOLD}------------------------------------------------------------${NC}"
echo "  Risk: VERY HIGH  Effort: VERY HIGH  Strategy: Refactor"
echo ""
echo "  10. monolith-erp          (Java EE monolith, 500K+ LOC)"
echo "      - Tightly coupled modules (HR, Finance, Procurement)"
echo "      - Migration: Strangler Fig pattern -- extract services one at a time"
echo "      - Action: Start with read-only APIs, decompose over 6+ months"
echo ""
echo "  11. legacy-auth-server    (Custom C++ LDAP proxy)"
echo "      - Requires root, binds to port 389"
echo "      - Migration: Replace with OpenShift OAuth / RHSSO (Keycloak)"
echo "      - Action: Map LDAP schema to RHSSO, migrate user data"
echo ""
echo "  12. realtime-dashboard    (Java applet + WebSocket server)"
echo "      - Relies on Java applets (deprecated technology)"
echo "      - Migration: Full rewrite to React + Node.js WebSocket"
echo "      - Action: Rewrite frontend, keep WebSocket backend"
echo ""

echo -e "${BOLD}============================================================${NC}"
echo -e "${BOLD}     Summary${NC}"
echo -e "${BOLD}============================================================${NC}"
echo ""
echo "  Wave 1:  3 apps  |  2 weeks  |  Low risk"
echo "  Wave 2:  3 apps  |  4 weeks  |  Medium risk"
echo "  Wave 3:  3 apps  |  6 weeks  |  High risk"
echo "  Wave 4:  3 apps  |  8+ weeks |  Very high risk"
echo ""
echo "  Total:  12 apps  |  20+ weeks estimated"
echo ""
echo -e "${CYAN}Recommendation:${NC}"
echo "  Start with Wave 1 to build team confidence and establish"
echo "  migration patterns. Each wave builds on lessons learned"
echo "  from the previous wave. Schedule retrospectives between waves."
echo ""
echo -e "${CYAN}Key Decision Points:${NC}"
echo "  - Wave 3, App 8 (.NET Framework): Rewrite to .NET 8 or run as VM?"
echo "  - Wave 4, App 10 (Monolith ERP): Strangler Fig timeline depends"
echo "    on business priority and team capacity."
echo "  - Wave 4, App 11 (C++ LDAP): Replace vs containerize?"
echo ""
