apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: analytics-service-monitor
  labels:
    app: shopinsights
    component: analytics-service
    tutorial: personalized
    lesson: "07"
spec:
  selector:
    matchLabels:
      app: shopinsights
      component: analytics-service
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
      scheme: http
