# ImageStream — an empty ImageStream for nginx that we will populate
# with tags by importing external images.
# See also: deployment.yaml for a workload that references this ImageStream.
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: my-nginx
  labels:
    app: my-nginx
    tutorial-level: "1"
    tutorial-module: "M3"
