# Service that exposes the console-demo-app Deployment on port 8080.
apiVersion: v1
kind: Service
metadata:
  name: console-demo-app
  labels:
    app: console-demo-app
    tutorial-level: "1"
    tutorial-module: "M1"
spec:
  selector:
    app: console-demo-app
  ports:
    - name: 8080-tcp
      port: 8080
      targetPort: 8080
      protocol: TCP
