# Kustomize base layer -- lists all resources in the base configuration.
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  tutorial-level: "1"
  tutorial-module: "M3"

resources:
  - deployment.yaml
  - service.yaml
  - route.yaml
