#!/usr/bin/env bash
# L05 — Service Mesh Demo: canary deployment, circuit breaker, network policy, observability
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
LESSON_DIR="$(dirname "$SCRIPT_DIR")"

step() { echo "" && echo "=== Step $1: $2 ===" && echo ""; }

oc project shopinsights

# --- Step 10: Canary Deployment ---
step 10 "Deploy canary version of Analytics Service"

echo "Adding version=v1 label to existing deployment..."
oc patch deployment analytics-service -n shopinsights \
  -p '{"spec":{"template":{"metadata":{"labels":{"version":"v1"}}}}}'

echo "Creating v1-only Service..."
oc apply -f "$LESSON_DIR/manifests/analytics-service-v1.yaml"

echo "Creating v2 Deployment..."
oc apply -f "$LESSON_DIR/manifests/analytics-deployment-v2.yaml"

echo "Creating v2-only Service..."
oc apply -f "$LESSON_DIR/manifests/analytics-service-v2.yaml"

echo "Labeling version services to use waypoint..."
oc label service analytics-service-v1 -n shopinsights istio.io/use-waypoint=waypoint --overwrite
oc label service analytics-service-v2 -n shopinsights istio.io/use-waypoint=waypoint --overwrite

echo "Waiting for v2 pod to be ready..."
until oc get pods -n shopinsights -l version=v2,component=analytics-service 2>/dev/null | grep -q "1/1"; do
  echo -n "."
  sleep 5
done
echo " Ready!"

echo "Applying HTTPRoute for 90/10 canary split..."
oc apply -f "$LESSON_DIR/manifests/httproute-analytics.yaml" -n shopinsights

echo ""
echo "Testing canary split (20 requests — expect ~18 v1, ~2 v2):"
for i in $(seq 1 20); do
  oc exec deploy/dashboard-ui -n shopinsights -- \
    curl -s http://analytics-service:8080/healthz 2>/dev/null
  echo ""
done

# --- Step 11: Circuit Breaker ---
step 11 "Apply circuit breaker for Orders Service"
oc apply -f "$LESSON_DIR/manifests/destination-rule-orders.yaml" -n shopinsights
echo "DestinationRule applied:"
oc get destinationrule -n shopinsights

# --- Step 12: Kiali Dashboard ---
step 12 "Kiali Dashboard + traffic generation"
KIALI_HOST=$(oc get route kiali -n istio-system -o jsonpath='{.spec.host}' 2>/dev/null || echo "")
if [ -n "$KIALI_HOST" ]; then
  echo "Kiali URL: https://${KIALI_HOST}"
else
  echo "Kiali route not found — check if the Kiali operator created a route in istio-system."
fi

echo ""
echo "Generating traffic for the service graph (10 requests)..."
for i in $(seq 1 10); do
  oc exec deploy/dashboard-ui -n shopinsights -- \
    curl -s http://products-service:8080/products > /dev/null 2>&1 || true
  oc exec deploy/dashboard-ui -n shopinsights -- \
    curl -s http://orders-service:8080/orders > /dev/null 2>&1 || true
done
echo "Traffic generation complete. Open Kiali and navigate to Graph > shopinsights."

# --- Step 13: Network Policy ---
step 13 "Apply Network Policy (defense in depth)"
oc apply -f "$LESSON_DIR/manifests/network-policy.yaml" -n shopinsights
echo "NetworkPolicy applied:"
oc get networkpolicy -n shopinsights

# --- Step 14: Distributed Tracing ---
step 14 "Distributed Tracing (OpenShift Console + Jaeger UI)"
CONSOLE_HOST=$(oc get route console -n openshift-console -o jsonpath='{.spec.host}' 2>/dev/null || echo "")
if [ -n "$CONSOLE_HOST" ]; then
  echo "OpenShift Console Traces: https://${CONSOLE_HOST}/observe/traces"
  echo "  1. Select Tempo instance: istio-system / sample"
  echo "  2. Tenant: dev"
  echo "  3. Filter by Service Name, then click a trace for the span waterfall"
fi

TEMPO_HOST=$(oc get route tempo-sample-jaegerui -n istio-system -o jsonpath='{.spec.host}' 2>/dev/null || echo "")
if [ -n "$TEMPO_HOST" ]; then
  echo ""
  echo "Jaeger UI (legacy): https://${TEMPO_HOST}"
fi
echo ""
echo "Note: HTTP traces are generated by the waypoint proxy."
echo "Only services labeled with istio.io/use-waypoint produce HTTP-level spans."

echo ""
echo "=== L05 Demo Complete ==="
echo "Canary split, circuit breaker, network policy, and observability are active."
echo "Next lesson: cd ../L06_auth_and_identity"
