# Namespace for the OpenShift Logging operator and its components
# This namespace must exist before installing the logging operators
apiVersion: v1
kind: Namespace
metadata:
  name: openshift-logging
  labels:
    app: openshift-logging
    tutorial-level: "1"
    tutorial-module: "M6"
  annotations:
    openshift.io/node-selector: ""
