# Istio Gateway to expose the canary-demo service outside the mesh.
# In OpenShift, you also need a Route pointing to the istio-ingressgateway
# service for external access.
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: canary-demo-gateway
  labels:
    app: canary-demo
    tutorial-level: "2"
    tutorial-module: "M3"
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "canary-demo.bookinfo-mesh.apps-crc.testing"
