# CrunchyData PGO (Postgres Operator) — Subscription to install via OLM
# This installs the operator from OperatorHub into the specified namespace
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: crunchy-postgres-operator
  namespace: openshift-operators
  labels:
    tutorial-level: "2"
    tutorial-module: "M2"
spec:
  channel: v5
  name: crunchy-postgres-operator
  source: certified-operators
  sourceNamespace: openshift-marketplace
  installPlanApproval: Automatic
