# OperatorGroup for the automatic-approval demo namespace
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: etcd-auto-demo-og
  namespace: etcd-auto-demo
  labels:
    app: etcd-auto-demo
    tutorial-level: "2"
    tutorial-module: "M2"
spec:
  targetNamespaces:
    - etcd-auto-demo
